Revert "If suite name isn't defined, will problem reoccur?"
Without suite name; "chef exec rake style" fails

Fix error:

[demo@demos-MacBook-Pro:chef_dotfiles(master)]$ chef exec rake style
rake aborted!
TypeError: no implicit conversion of nil into String
/Users/demo/pdev/TaylorMonacelli/chef_dotfiles/Rakefile:49:in `new'
/Users/demo/pdev/TaylorMonacelli/chef_dotfiles/Rakefile:49:in `block in
<top (required)>'
/Users/demo/pdev/TaylorMonacelli/chef_dotfiles/Rakefile:44:in
`<top (required)>'
(See full trace by running task with --trace)
[demo@demos-MacBook-Pro:chef_dotfiles(master)]$ g s
On branch master

This reverts commit 2d64285e5d5ba31fb200d5a716a35bb1d05397ad.